-- Level 12: Gather/Concat/Split
local helpers = require("tests.test_helpers")
local test = helpers.test
local assert_eq = helpers.assert_eq

local nn = lua_nn

print("\n========== Level 12: Gather/Concat/Split ==========\n")

test("gather - 1D索引", function()
    local src = nn.Tensor.new({0, 10, 20, 30, 40}, {5})
    local idx = nn.Tensor.new({4, 0, 2}, {3})
    local result = src:gather(0, idx)
    local shape = result:shape()
    assert_eq(shape[1], 3, "gather 1D shape")
    assert_eq(result:get(0), 40, "gather[0]")
    assert_eq(result:get(1), 0, "gather[1]")
    assert_eq(result:get(2), 20, "gather[2]")
end)

test("gather - 2D沿axis=1", function()
    local src = nn.Tensor.new({1,2,3,4,5,6}, {2, 3})
    local idx = nn.Tensor.new({0, 2, 1, 0}, {2, 2})
    local result = src:gather(1, idx)
    local shape = result:shape()
    assert_eq(shape[1], 2, "gather 2D rows")
    assert_eq(shape[2], 2, "gather 2D cols")
    assert_eq(result:get(0), 1, "gather[0,0] = src[0,0]")
    assert_eq(result:get(1), 3, "gather[0,1] = src[0,2]")
    assert_eq(result:get(2), 5, "gather[1,0] = src[1,1]")
    assert_eq(result:get(3), 4, "gather[1,1] = src[1,0]")
end)

test("concat - 沿axis=0", function()
    local t1 = nn.Tensor.new({1, 2, 3}, {1, 3})
    local t2 = nn.Tensor.new({4, 5, 6}, {1, 3})
    local t3 = nn.Tensor.new({7, 8, 9}, {1, 3})
    local result = nn.Tensor.concat({t1, t2, t3}, 0)
    local shape = result:shape()
    assert_eq(shape[1], 3, "concat axis=0 rows")
    assert_eq(shape[2], 3, "concat axis=0 cols")
    assert_eq(result:get(0), 1, "concat[0,0]")
    assert_eq(result:get(3), 4, "concat[1,0]")
    assert_eq(result:get(6), 7, "concat[2,0]")
end)

test("concat - 沿axis=1", function()
    local t1 = nn.Tensor.new({1, 2, 3, 4}, {2, 2})
    local t2 = nn.Tensor.new({5, 6, 7, 8}, {2, 2})
    local result = nn.Tensor.concat({t1, t2}, 1)
    local shape = result:shape()
    assert_eq(shape[1], 2, "concat axis=1 rows")
    assert_eq(shape[2], 4, "concat axis=1 cols")
    assert_eq(result:get(0), 1, "concat[0,0]")
    assert_eq(result:get(1), 2, "concat[0,1]")
    assert_eq(result:get(2), 5, "concat[0,2]")
    assert_eq(result:get(3), 6, "concat[0,3]")
end)

test("split - 均匀分割", function()
    local t = nn.Tensor.new({1,2,3,4,5,6,7,8,9,10,11,12}, {4, 3})
    local parts = t:split(2, 0)
    assert_eq(#parts, 2, "split count")
    local shape1 = parts[1]:shape()
    local shape2 = parts[2]:shape()
    assert_eq(shape1[1], 2, "split[0] rows")
    assert_eq(shape1[2], 3, "split[0] cols")
    assert_eq(shape2[1], 2, "split[1] rows")
    assert_eq(parts[1]:get(0), 1, "split[0][0,0]")
    assert_eq(parts[1]:get(3), 4, "split[0][1,0]")
    assert_eq(parts[2]:get(0), 7, "split[1][0,0]")
    assert_eq(parts[2]:get(3), 10, "split[1][1,0]")
end)

test("split - 沿axis=1", function()
    local t = nn.Tensor.new({1,2,3,4,5,6,7,8}, {2, 4})
    local parts = t:split(2, 1)
    assert_eq(#parts, 2, "split count")
    local shape = parts[1]:shape()
    assert_eq(shape[1], 2, "split rows")
    assert_eq(shape[2], 2, "split cols")
    assert_eq(parts[1]:get(0), 1, "split[0][0,0]")
    assert_eq(parts[1]:get(1), 2, "split[0][0,1]")
    assert_eq(parts[2]:get(0), 3, "split[1][0,0]")
    assert_eq(parts[2]:get(1), 4, "split[1][0,1]")
end)

test("concat + split 往返", function()
    local t1 = nn.Tensor.new({1, 2, 3, 4}, {2, 2})
    local t2 = nn.Tensor.new({5, 6, 7, 8}, {2, 2})
    local concat_result = nn.Tensor.concat({t1, t2}, 0)
    local parts = concat_result:split(2, 0)
    assert_eq(parts[1]:get(0), 1, "roundtrip[0][0]")
    assert_eq(parts[1]:get(3), 4, "roundtrip[0][3]")
    assert_eq(parts[2]:get(0), 5, "roundtrip[1][0]")
    assert_eq(parts[2]:get(3), 8, "roundtrip[1][3]")
end)

return true
